export const services = [
  {
    id: 'frontend',
    title: 'Frontend implementation',
    problem: 'For teams with a design, feature, or product idea that needs experienced frontend ownership.',
    actions: ['Build responsive interfaces and reusable components', 'Integrate with your APIs and existing application', 'Test important user journeys and prepare a practical handover'],
    outcome: 'A polished, maintainable interface that is ready for your users and team.',
  },
  {
    id: 'react-review',
    title: 'React application reviews',
    problem: 'For React applications that have become difficult to change, test, or reason about.',
    actions: ['Review component structure and maintainability', 'Assess usability, performance, and testing gaps', 'Prioritise improvements by impact and effort'],
    outcome: 'A clear, practical plan for improving your frontend without a rewrite.',
  },
  {
    id: 'node-upgrade',
    title: 'Node.js upgrades',
    problem: 'For applications stuck on an ageing Node.js version or blocked by incompatible dependencies.',
    actions: ['Assess dependency and runtime compatibility', 'Upgrade application dependencies incrementally', 'Resolve breaking changes and regressions', 'Verify build, test, and deployment configuration'],
    outcome: 'A maintainable application running on a supported Node.js version.',
  },
  {
    id: 'testing',
    title: 'Automated testing',
    problem: 'For teams where changes feel risky because important behaviour is not covered by tests.',
    actions: ['Identify the user journeys and risks worth protecting', 'Add focused unit, integration, or end-to-end tests', 'Connect tests to your development and CI workflow'],
    outcome: 'More confidence in releases and faster feedback when changes break something important.',
  },
  {
    id: 'ongoing-support',
    title: 'Fractional frontend engineering',
    label: 'Ongoing / retainer',
    problem: 'For product teams with ongoing development needs that need experienced frontend capacity alongside their existing developers.',
    actions: ['Reserve recurring capacity for planned feature work', 'Maintain and improve existing interfaces', 'Support integrations, bug fixes, and technical improvements', 'Collaborate with your developers and product team on priorities'],
    outcome: 'Consistent senior frontend support that keeps your product moving forward.',
  },
];

export const projects = [
  {
    title: 'Sweepsouth',
    productType: 'Marketplace web application',
    context: 'A production service marketplace needed frontend development within an existing product team, including interfaces connected to its backend systems.',
    role: 'Frontend engineer in a product team.',
    delivered: ['Built React interfaces connected to a Python API through GraphQL', 'Created Django admin templates for operational workflows', 'Added automated coverage with Jest and Cypress'],
    result: 'Shipped production React interfaces and protected key user flows with automated tests.',
    tags: ['React', 'GraphQL', 'Django'],
    link: 'https://sweepsouth.com/',
  },
  {
    title: 'DoubleExposure',
    productType: 'Web and desktop product',
    context: 'The product needed a customer-facing web frontend and a supporting upload workflow that could work with its existing backend.',
    role: 'Frontend engineer across web and desktop interfaces.',
    delivered: ['Built web interfaces with Handlebars and Semantic UI', 'Developed an Electron upload helper application', 'Integrated both experiences with a Groovy API'],
    result: 'Delivered a connected web and desktop workflow for the product’s upload process.',
    tags: ['JavaScript', 'Electron', 'Grails'],
    link: 'https://www.doubleexposure.co/',
  },
  {
    title: 'RouxtAccess',
    productType: 'Business website',
    context: 'The business needed a responsive web presence that could communicate its offer, be found by search engines, and capture enquiries.',
    role: 'Frontend developer and site implementer.',
    delivered: ['Implemented custom HTML and SCSS styling', 'Set up analytics and Firebase hosting', 'Added a Formspree enquiry form'],
    result: 'Launched a responsive, SEO-ready website with analytics and a direct enquiry path.',
    tags: ['HTML & SCSS', 'Firebase', 'Formspree'],
  },
];
